module Retsly
  module Models
    # rubocop:disable Metrics/ClassLength
    class Listing
      extend ::ModelAttribute
      attr_accessor :client
      attribute :id,                          :string
      attribute :mls_listing_id,              :string
      attribute :address,                     :string
      attribute :unit_number,                 :string
      attribute :street_name,                 :string
      attribute :street_number,               :string
      attribute :city,                        :string
      attribute :state,                       :string
      attribute :county,                      :string
      attribute :country,                     :string
      attribute :zip_code,                    :string
      attribute :subdivision,                 :string
      attribute :coordinates,                 :json
      attribute :list_date,                   :time
      attribute :last_modified,               :string
      attribute :price,                       :json
      attribute :previous_price,              :json
      attribute :original_price,              :json
      attribute :close_price,                 :json
      attribute :buyer_financing,             :string
      attribute :contingency,                 :string
      attribute :disclosures,                 :json
      attribute :units_in_building,           :integer
      attribute :cancelation_date,            :time
      attribute :expiration_date,             :time
      attribute :terms_of_sale,               :json
      attribute :date_listed,                 :string
      attribute :date_sold,                   :time
      attribute :status_change,               :string
      attribute :ownership,                   :string
      attribute :financial_data_source,       :string
      attribute :year_built,                  :integer
      attribute :year_built_details,          :string
      attribute :days_on_market,              :integer
      attribute :appliances,                  :json
      attribute :telephone_service,           :json
      attribute :view,                        :json
      attribute :waterfront,                  :boolean
      attribute :water_source,                :json
      attribute :zoning,                      :string
      attribute :zoning_description,          :string
      attribute :acres,                       :json
      attribute :square_footage,              :integer
      attribute :living_area,                 :integer
      attribute :above_grade_finished_area,   :integer
      attribute :below_grade_finished_area,   :integer
      attribute :stories,                     :integer
      attribute :stories_total,               :integer
      attribute :baths,                       :integer
      attribute :half_baths,                  :integer
      attribute :bedrooms,                    :integer
      attribute :rooms_total,                 :integer
      attribute :fireplaces,                  :integer
      attribute :fireplace_features,          :json
      attribute :exterior_features,           :json
      attribute :new_construction,            :boolean
      attribute :home_warranty,               :boolean
      attribute :architectural_style,         :json
      attribute :community_features,          :json
      attribute :patio_and_porch_features,    :json
      attribute :lot_features,                :json
      attribute :basement,                    :json
      attribute :other_structures,            :json
      attribute :pets_allowed,                :json
      attribute :flooring,                    :json
      attribute :foundation_details,          :json
      attribute :frontage_length,             :integer
      attribute :gas,                         :json
      attribute :accessibility_features,      :json
      attribute :cooling,                     :json
      attribute :heating,                     :json
      attribute :parcel_number,               :string
      attribute :additional_parcels,          :boolean
      attribute :occupant_type,               :string
      attribute :pool,                        :boolean
      attribute :pool_features,               :json
      attribute :pool_private,                :boolean
      attribute :possession,                  :json
      attribute :road_surface,                :json
      attribute :roof,                        :json
      attribute :construction_materials,      :json
      attribute :sewer,                       :json
      attribute :garage_spaces,               :integer
      attribute :carport_spaces,              :integer
      attribute :open_parking,                :boolean
      attribute :attached_garage,             :boolean
      attribute :carport,                     :boolean
      attribute :laundry,                     :json
      attribute :type,                        :string
      attribute :subtype,                     :string
      attribute :public_remarks,              :string
      attribute :private_remarks,             :string
      attribute :media,                       :json
      attribute :agent,                       :string
      attribute :mls_agent_id,                :string
      attribute :office,                      :string
      attribute :mls_office_id,               :string
      attribute :status,                      :string
      attribute :contract_status_change_date, :time
      attribute :contingent_date,             :time
      attribute :withdrawn_date,              :time
      attribute :off_market_date,             :time
      attribute :purchase_contract_date,      :time
      attribute :original_entry_timestamp,    :time
      attribute :tax_assessed_value,          :json
      attribute :tax_annual,                  :json
      attribute :tax_year,                    :integer
      attribute :tax_status,                  :json
      attribute :association,                 :boolean
      attribute :association_name,            :string
      attribute :association_fee,             :json
      attribute :association_fee_frequency,   :string
      attribute :listing_agent_first_name,    :string
      attribute :listing_agent_last_name,     :string
      attribute :listing_agent_middle_name,   :string
      attribute :listing_agent_full_name,     :string
      attribute :listing_agent_phone,         :string
      attribute :listing_office_name,         :string
      attribute :listing_office_phone,        :string
      attribute :url,                         :string

      def initialize(attributes = {})
        set_attributes(attributes)
      end
    end
  end
end
